# Тензоры

In [1]:
import torch
import numpy as np

## Инициализация тензора

### Из данных

In [12]:
data = [
    [1, 2],
    [3, 4]
]
tensor_1 = torch.tensor(data) # dtype = torch.int64
tensor_1

tensor([[1, 2],
        [3, 4]])

### Из массива numpy

In [ ]:
np_array = np.array(data)
tensor_2 = torch.tensor(np_array) # dtype = torch.int64
tensor_2

tensor([[1, 2],
        [3, 4]])

### Из другого тензора

In [15]:
ones_tensor = torch.ones_like(tensor_2)
rand_tensor = torch.rand_like(tensor_1, dtype=torch.float32)
print(f'ones_tensor:\n{ones_tensor}')
print(f'rand_tensor:\n{rand_tensor=}')

ones_tensor:
tensor([[1, 1],
        [1, 1]])
rand_tensor:
rand_tensor=tensor([[0.4252, 0.2388],
        [0.1679, 0.0110]])


### Случайные или постоянные значения

In [16]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)

print(f'rand:\n{rand_tensor}')
print(f'zeros:\n{zeros_tensor}')
print(f'ones:\n{ones_tensor}')

rand:
tensor([[0.7240, 0.4192, 0.1790],
        [0.7715, 0.3399, 0.7513]])
zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Атрибуты тензора

In [18]:
tensor = torch.rand(3, 4)

print(f'shape: {tensor.shape}')
print(f'size: {tensor.size()}')
print(f'ndim: {tensor.ndim}')
print(f'type: {tensor.dtype}')
print(f'device: {tensor.device}')

shape: torch.Size([3, 4])
size: torch.Size([3, 4])
ndim: 2
type: torch.float32
device: cpu


## Операции на тензорах

### Индексация

In [28]:
tensor = torch.ones(5, 5)

print(f'First row: {tensor[0]}')
print(f'First col: {tensor[:, 0]}')
print(f'Last col: {tensor[:, -1]}')
tensor[...,0] = 0
print(tensor)

First row: tensor([1., 1., 1., 1., 1.])
First col: tensor([1., 1., 1., 1., 1.])
Last col: tensor([1., 1., 1., 1., 1.])
tensor([[0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.]])


### Конкатенация

In [32]:
t = torch.cat([tensor, tensor], dim=1)
t

tensor([[0., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 0., 1., 1., 1., 1.]])

### Арифметические операции

In [38]:
t1 = torch.rand((2, 3))
t2 = torch.rand((3, 4))
print(f't1:\n{t1}')
print(f't2:\n{t2}')

t3 = t1 @ t2
t4 = t1.matmul(t2)
print(f't1 @ t2 =\n{t3}')
print(f't1.matmul(t.2) = \n{t4}')

t5 = t1 * t1
t6 = t1.mul(t1)
print(f't1 * t1 =\n{t5}')
print(f't1.mul(t1) = \n{t6}')



t1:
tensor([[0.4727, 0.4801, 0.5096],
        [0.7301, 0.4131, 0.9940]])
t2:
tensor([[0.7727, 0.0702, 0.0862, 0.1206],
        [0.2286, 0.3064, 0.6485, 0.1814],
        [0.0160, 0.1923, 0.0771, 0.2035]])
t1 @ t2 =
tensor([[0.4831, 0.2783, 0.3914, 0.2478],
        [0.6745, 0.3690, 0.4074, 0.3652]])
t1.matmul(t.2) = 
tensor([[0.4831, 0.2783, 0.3914, 0.2478],
        [0.6745, 0.3690, 0.4074, 0.3652]])
t1 * t1 =
tensor([[0.2234, 0.2305, 0.2597],
        [0.5331, 0.1706, 0.9881]])
t1.mul(t1) = 
tensor([[0.2234, 0.2305, 0.2597],
        [0.5331, 0.1706, 0.9881]])


### item()

In [36]:
s = t1.sum()
s.item()

4.232490539550781

### Операции на месте

Операции, которые хранят результат в операнде, называются на месте. Они обозначаются через _ в конце. Например, к примеру: x.copy_(y), x.t_(), изменится x.

In [41]:
tensor = torch.rand(2,2)
print(tensor)
tensor.add_(10)
print(f'After tensor.add_(10):\n{tensor}')
tensor.add(100)
print(f'After tensor.add(10):\n{tensor}')

tensor([[0.9471, 0.5240],
        [0.4699, 0.1897]])
After tensor.add_(10):
tensor([[10.9471, 10.5240],
        [10.4699, 10.1897]])
After tensor.add(10):
tensor([[10.9471, 10.5240],
        [10.4699, 10.1897]])


## Связь с Numpy

### Тензор в Numpy массив

Изменение тензора отражается в массиве NumPy.

In [46]:
t = torch.rand(2,2)
n = t.numpy()

print(t)
print(n)

t.add_(10)
print(t)
print(n)


tensor([[0.4757, 0.7527],
        [0.0326, 0.8434]])
[[0.47567207 0.75272   ]
 [0.0325895  0.84336406]]
tensor([[10.4757, 10.7527],
        [10.0326, 10.8434]])
[[10.475672 10.75272 ]
 [10.03259  10.843364]]


### Массив NumPy для Tensor 

In [47]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]
